export {
  NativeWorkspaceSyncBridgeError,
  computeNativeDirectoryFingerprint,
  computeNativeDirectoryFingerprintBatch,
  isNativeWorkspaceSyncEnabled,
  planNativeLocalToRemote,
  resolveWorkspaceSyncBinary,
  scanNativeLocalTree,
  shutdownNativeWorkspaceSyncWorkerPool,
  runWorkspaceSyncVersion,
  type NativeDirectoryFingerprintInput,
  type NativeDirectoryFingerprintBatchEntry,
  type NativeDirectoryFingerprintBatchResult,
  type NativeDirectoryFingerprintResult,
  type NativePlanLocalToRemoteResult,
  type NativePlanSeedUploadResult,
  type NativePlanDownloadCandidate,
  type NativePlanRemoteEntry,
  type NativePlanUploadCandidate,
  type NativePlanRemoteToLocalResult,
  type NativeSeedUploadFile,
  type NativeSandboxHttpConfig,
  type NativeSyncLocalToSandboxHttpResult,
  type NativeSyncLocalToRemoteResult,
  type NativeSyncRemoteToLocalResult,
  type NativeWorkspaceSyncObjectStoreConfig,
  planNativeRemoteToLocal,
  planNativeSeedUpload,
  syncNativeLocalToSandboxHttp,
  syncNativeLocalToRemote,
  syncNativeRemoteToLocal,
  type NativeScanLocalTreeResult,
  type NativeScannedFileEntry,
  type NativeWorkspaceSyncVersionResult
} from "./workspace-sync.js";
